[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ACES"
version = "0.2.0"
authors = [
  { name="Justin Xu", email="justin13601@hotmail.com" },
  { name="Matthew McDermott", email="mattmcdermott8@gmail.com" },
]
description = "Event Stream Automatic Cohort Extraction System"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "polars == 0.20.18",
    "bigtree == 0.17.0",
    "ruamel.yaml == 0.18.6",
    "pandas == 2.2.2",
    "loguru == 0.7.2",
    "hydra-core == 1.3.2",
    "pytimeparse == 1.1.8",
    "networkx == 3.3",
]

[project.optional-dependencies]
dev = [
  "pre-commit", "pytest", "pytest-cov", "pytest-subtests", "rootutils"
]
profiling = ["psutil"]

[project.urls]
Homepage = "https://github.com/justin13601/ACES"
Issues = "https://github.com/justin13601/ACES/issues"
